### ISSUE TITLE
Unreal Source 5.1 compile

### ISSUE THREAD

**Issue by ChrisFriendly** [eidosmontreal/unreal-vdb#29]
Hello!
Can someone please help me to get this to compile with UE 5.1?
thanks

**Comment by thilamb** [comment]
We will not support UE 5.1 until its official release because Epic will integrate a lot more changes until the release.

If you paste your errors here I might be able to help / guess the fix.

**Comment by ChrisFriendly** [comment]
Thanks

here are the errors I got so far:

[18/60] Compile VolumeMesh.cpp
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(25): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(26): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(27): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(28): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(30): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(31): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(32): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(33): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(43): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(44): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(44): error C2660: 'FStaticMeshVertexBuffer::SetVertexTangents': function does not take 3 arguments
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Public\Rendering\StaticMeshVertexBuffer.h(293): note: see declaration of 'FStaticMeshVertexBuffer::SetVertexTangents'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(45): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(45): error C2660: 'FStaticMeshVertexBuffer::SetVertexUV': function does not take 2 arguments
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Public\Rendering\StaticMeshVertexBuffer.h(323): note: see declaration of 'FStaticMeshVertexBuffer::SetVertexUV'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VolumeMesh.cpp(46): error C2027: use of undefined type 'FDynamicMeshVertex'
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\ConvexElem.h(14): note: see declaration of 'FDynamicMeshVertex'
[19/60] Compile VdbBlueprintLibrary.cpp
[20/60] Compile VdbPrincipledSceneProxy.cpp
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VdbPrincipledSceneProxy.cpp(136): error C2027: use of undefined type 'FRDGBuilder'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VdbDenoiser.h(21): note: see declaration of 'FRDGBuilder'

[19/60] Compile VdbBlueprintLibrary.cpp
[20/60] Compile VdbPrincipledSceneProxy.cpp
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VdbPrincipledSceneProxy.cpp(136): error C2027: use of undefined type 'FRDGBuilder'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VdbDenoiser.h(21): note: see declaration of 'FRDGBuilder'

[42/60] Compile VdbAssetTypeActions.cpp
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Importer\Private\VdbAssetTypeActions.cpp(61): error C2653: 'FEditorStyle': is not a class or namespace name
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Importer\Private\VdbAssetTypeActions.cpp(61): error C3861: 'GetStyleSetName': identifier not found
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Importer\Private\VdbAssetTypeActions.cpp(57): error C2664: 'FToolMenuEntry &FToolMenuSection::AddMenuEntry(const TSharedPtr<const FUICommandInfo,ESPMode::ThreadSafe> &,const TAttribute<FText> &,const TAttribute<FText> &,const TAttribute<FSlateIcon> &,const FName,const TOptional<FName>)': cannot convert argument 1 from 'const char [30]' to 'const TSharedPtr<const FUICommandInfo,ESPMode::ThreadSafe> &'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Importer\Private\VdbAssetTypeActions.cpp(66): note: Reason: cannot convert from 'const char [30]' to 'const TSharedPtr<const FUICommandInfo,ESPMode::ThreadSafe>'
F:\GitHub\unreal_vdb_built\HostProject\Plugins\SparseVolumetrics\Source\Importer\Private\VdbAssetTypeActions.cpp(66): note: No constructor could take the source type, or constructor overload resolution was ambiguous
D:\UE5_GitHub_Builds\UnrealEngine-ue5-main\Engine\Source\Developer\ToolMenus\Public\ToolMenuSection.h(38): note: see declaration of 'FToolMenuSection::AddMenuEntry'

**Comment by thilamb** [comment]
That's a lot of different errors, I'm afraid it will take a bit more work to make it compatible. 
Do you really need the unfinished 5.1 ?

Not saying I will do it, but if I get bored someday I will convert the plugin in a separate branch and will let you know if this happens.

**Comment by ChrisFriendly** [comment]
We decided to use it because of nanite working with foliage (for the most part..)
the vdb plugin is not essential as we could go the flipbook way but would be nice to have

thanks!

**Comment by thilamb** [comment]
As soon as I find a way to compile 5.1 on my machine (I have a weird issue right now), I will work on upgrading the plugin.

**Comment by thilamb** [comment]
I fixed the errors in the 5.1 branch: https://github.com/eidosmontreal/unreal-vdb/tree/5.1

Please let me know if it now works on your side.

Thanks

**Comment by ChrisFriendly** [comment]
awesome!
it worked without problems.
thanks!
