### ISSUE TITLE
Fatal Error when packaging UE5 project

### ISSUE THREAD

**Issue by samxyz1** [eidosmontreal/unreal-vdb#42]
Hello ! I'm facing a problem using your very useful plugin when I'm trying to package my project. 

First thing, I packaged project with only the Bunny VDB file from your examples, and the .exe is running fine.

Then, when I import my own VDB file, everything works fine in the Editor. But when I package the project with my custom VDB, I can't run the .exe, I have a "Fatal Error" popup, as you can see on the attached file.

![Screenshot 2022-10-20 122744](https://user-images.githubusercontent.com/45818754/196924889-1474b6c2-a6ec-4cc5-be72-a33baf04549a.png)

Here is the call stack from the log:

[  0]LogWindows: Error: [Callstack] 0x00007ff73868cc91 PROJECT.exe!FVdbMaterialRendering::ReleaseRendering() [E:\UnrealProjects\UE5Projects\PROJECT\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VdbMaterialRendering.cpp:290]
[  0]LogWindows: Error: [Callstack] 0x00007ff738680348 PROJECT.exe!FVdbMaterialRendering::InitRendering() [E:\UnrealProjects\UE5Projects\PROJECT\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VdbMaterialRendering.cpp:278]
[  0]LogWindows: Error: [Callstack] 0x00007ff73866c006 PROJECT.exe!TGraphTask<TEnqueueUniqueRenderCommandType<`FVdbMaterialRendering::Init'::`7'::InitVdbRenderingName,<lambda_3c1c3e37041d80d6423f71ec36e80586> > >::ExecuteTask() [C:\Program Files\Epic Games\UE_5.1\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:1351]

We tried to run it on both a RTX 3080 and a 3090. We tried with UE5.0.3 and 5.1 preview.

Since the Bunny is working fine, I guess the problem is coming from my VDB file. What kind of parameters should I take care of while exporting from Houdini / importing to Unreal ?

Thanks a lot.

**Comment by thilamb** [comment]
Hello, the bunny VDB comes from openvdb.org and I don't see how why other parameters would mess with the packaging. 

Would you be able to share (privately) your project with me ? I've never seen this issue before but if I can reproduce it on my computer I will most probably be able to help.

**Comment by arturleao** [comment]
I'm getting the exact same problem, latest release, Unreal 5.1, how did you solve this?

**Comment by thilamb** [comment]
They never answered so I closed the issue.

Can you try with the plugin in your project/game folder (and not in the
engine folder) ?

I haven’t tried packaging for a while, I’ll try it tomorrow just in case.

Can you share your project so I can try debugging this issue ?

**Comment by arturleao** [comment]
Thanks for the quick reply... I already have the plugin in the game folder... Can't share the project unfortunately. But the error is exactly the same, we're trying to solve it on our side but would be great if you had any insight. It looks like the pointer to the texture is lost/never assigned, something like that. Works fine in the editor though.

**Comment by thilamb** [comment]
I've been able to package a project on my side and make it run. 

Is there any additional info that you could share to help me understand the issue ?

Can you check that you're using 0.6.4 and not 0.6.3 ? 
What VDB types are you using ? VdbPrincipled or VdbMaterial ? Are you using Temperature / Color VDBs ? 
Any non-default export / packaging options that I should know about ?

Thanks

**Comment by arturleao** [comment]
I've tested all versions you have that work on UE5.1, all crash. It crashes with both principled and material... I'm using cloud 10 from embergen cloud pack. no temperature nor color. Nothing special on the packaging. Using Lumen and Nanite.

**Comment by doppioslash** [comment]
I had a similar problem due to some of the plugin's shaders not compiling for the packaged build.

In the end it was the interaction between an older GPU (an Nvidia GTX) and the project settings allowing support for Shader Model 5 & DirextX11. 
If you are compiling on a machine with an older GPU, in the project settings try disabling DX11 and SM5, and set DX12 and SM6 as defaults.

**Comment by azjata** [comment]
For me it does not package either. 
Neither Unreal 5.1 Stock or 5.1 sources does not package
If you dig deeper there is a ShaderCompilation error

**Comment by doppioslash** [comment]
I have been able to package with 5.1, by solving a shader compilation error.
My particular case seemed to be caused by compiling on a machine with an older GPU (GTX) while having DirectX11 and shader model 5 enabled in the project settings.
I forced DirectX12 and SM6 only and my packaging issue was fixed.

It may or may not be the same issue as everybody else, I don't have the error logs at hand.

**Comment by arturleao** [comment]
My project is DX12 and SM6 only and I still have the issue.

**Comment by thilamb** [comment]
A couple of days ago[ I fixed the packaging shader compilation error](https://github.com/eidosmontreal/unreal-vdb/commit/ffc827fc35e681b08c301ff9293add7358a4acd5) that happen sometimes. 

Today [I'm sharing a new Release with the fix](https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.5_ue5.1.0). Hopefully this will help everyone here. Please let me know if this doesn't fix packaging on your machines.

But if I understand correctly, samxyz1 and arturleao can package but the standalone game crashes at startup. Is that right ?
@arturleao could you try packaging with Debug mode and then send me the new crash callstack ? I'm sure it will be really easy to fix but I just need to be able to reproduce it first.

**Comment by arturleao** [comment]
> A couple of days ago[ I fixed the packaging shader compilation error](https://github.com/eidosmontreal/unreal-vdb/commit/ffc827fc35e681b08c301ff9293add7358a4acd5) that happen sometimes.
> 
> Today [I'm sharing a new Release with the fix](https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.5_ue5.1.0). Hopefully this will help everyone here. Please let me know if this doesn't fix packaging on your machines.
> 
> But if I understand correctly, samxyz1 and arturleao can package but the standalone game crashes at startup. Is that right ? @arturleao could you try packaging with Debug mode and then send me the new crash callstack ? I'm sure it will be really easy to fix but I just need to be able to reproduce it first.

Yes, that is pretty much it, I didn't get the shader compilation error, just the crash on start (in my case when switching to a scene that has VDBs), I'll update to your latest fix and will send the you the minidump. Cheers and thanks for looking into this.

**Comment by arturleao** [comment]
I tried the latest build and now I get this error: 

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

0x00007ff7d0ec7e00 copper_envs.exe!FSceneViewExtensions::RegisterExtension() []
0x00007ff7c97bfb5e copper_envs.exe!FSceneViewExtensions::NewExtension<FVdbMaterialRendering>() [D:\Epic Games\UE_5.1\Engine\Source\Runtime\Engine\Public\SceneViewExtension.h:293]
0x00007ff7c983dabb copper_envs.exe!FVolumeRuntimeModule::GetOrCreateRenderExtension() [E:\git\copper_wall\copper_envs\Plugins\SparseVolumetrics\Source\Runtime\Private\VolumeRuntimeModule.cpp:58]
0x00007ff7c9840795 copper_envs.exe!FVolumeRuntimeModule::GetRenderExtension() [E:\git\copper_wall\copper_envs\Plugins\SparseVolumetrics\Source\Runtime\Private\VolumeRuntimeModule.cpp:51]
0x00007ff7c97db260 copper_envs.exe!FVdbMaterialSceneProxy::FVdbMaterialSceneProxy() [E:\git\copper_wall\copper_envs\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VdbMaterialSceneProxy.cpp:39]
0x00007ff7c9806725 copper_envs.exe!UVdbMaterialComponent::CreateSceneProxy() [E:\git\copper_wall\copper_envs\Plugins\SparseVolumetrics\Source\Runtime\Private\VdbMaterialComponent.cpp:60]
0x00007ff7cdab53d4 copper_envs.exe!FScene::AddPrimitive() []
0x00007ff7d027544a copper_envs.exe!operator<<() []
0x00007ff7c968594b copper_envs.exe!`ParallelForImpl::ParallelForInternal<TFunctionRef<void __cdecl(int)>,<lambda_06f0d5d1c5fc9bccb0e7d1fd1e70ca42>,std::nullptr_t>'::`2'::FParallelExecutor::operator()() []
0x00007ff7c968c7a4 copper_envs.exe!LowLevelTasks::TTaskDelegate<LowLevelTasks::FTask * __ptr64 __cdecl(bool),48>::TTaskDelegateImpl<<lambda_cd5d35de258cbd13177d68cf0a207ffd>,0>::CallAndMove() []
0x00007ff7cb6dd9d5 copper_envs.exe!LowLevelTasks::FTask::ExecuteTask() []
0x00007ff7cb6dd767 copper_envs.exe!LowLevelTasks::FScheduler::ExecuteTask() []
0x00007ff7cb6c3fc8 copper_envs.exe!LowLevelTasks::FScheduler::TryExecuteTaskFrom<&LowLevelTasks::TLocalQueueRegistry<1024>::TLocalQueue::DequeueGlobal,0>() []
0x00007ff7cb6fe502 copper_envs.exe!LowLevelTasks::FScheduler::WorkerMain() []
0x00007ff7cb6cf410 copper_envs.exe!UE::Core::Private::Function::TFunctionRefCaller<FUniqueBuffer __cdecl(unsigned __int64),FUniqueBuffer __cdecl(unsigned __int64)>::Call() []
0x00007ff7cb83f809 copper_envs.exe!FThreadImpl::Run() []
0x00007ff7cbd76912 copper_envs.exe!FRunnableThreadWin::Run() []
0x00007ff7cbd6e710 copper_envs.exe!FRunnableThreadWin::GuardedRun() []
0x00007ff972567614 KERNEL32.DLL!UnknownFunction []
0x00007ff972d426a1 ntdll.dll!UnknownFunction []

Crash in runnable thread Foreground Worker #0

<img width="356" alt="image" src="https://user-images.githubusercontent.com/2388850/218254509-e9db73e0-dd87-4e23-82ba-f664d6746bc4.png">

Here's the minidump: https://we.tl/t-0tRXojsqM2

**Comment by thilamb** [comment]
Fixed with https://github.com/eidosmontreal/unreal-vdb/commit/4bf21547f283fed08feba7bd03b8f26ed989264e.

Thanks for reporting the crash ! Sorry for the long wait.
